language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pytest

env:
  - "TEST_DIR=Generator"

branches:
  only:
    - travis_test

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true