language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest -m pytest

branches:
  only:
    - travis_test

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true