language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - cd modules/Generator && pytest

env:
  - TEST_DIR=modules/Generator

branches:
  only:
    - travis_test

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true